"""The words a dictionary is worst at, written out by hand once.

Strong's is a good gloss for a noun and a poor one for a particle. Its entry for `דִּי`
— the commonest word in Daniel's Aramaic, 272 occurrences in the books measured — is a
paragraph beginning "that, used as relative conjunction, and especially (with a
preposition) in adverbial phrases", and its entry for `אֵת`, the direct-object marker
and the commonest word in the Hebrew Bible, is the sentence "[as such unrepresented in
English]". Neither is what a learner wants on a card.

They are also a closed set, which is what makes this worth writing rather than buying.
Counted over 39 books of the scripture shelf with the content words already glossed from
the lexicon, everything still without a meaning came to **174 Hebrew forms and 63
Aramaic ones** — and the top ten Hebrew forms are half of all of it. Written once here,
they are right in every text on the shelf for ever, and cost nothing.

**Keyed by lexeme number, not by spelling.** `לֹא` is `3808` in Hebrew and `3809` in
Aramaic; `אֵת` is `853` the object marker and `854` the preposition "with", and both are
spelled the same. A number says which word this is where no spelling can. The handful of
pieces the tagging numbers with a letter rather than a number — the pronominal suffixes,
`־ךָ` and `־הֶם` and the rest — are keyed by their written form instead, in `BY_FORM`.

**House style**: short, lower case, senses separated by a semicolon, the way the bought
glosses read. A grammatical note goes in brackets where the word does a job English does
not have a word for.
"""

from __future__ import annotations

#: Hebrew, by Strong's number. Ordered as the corpus orders them, commonest first, so
#: the top of this list is the part that matters and the bottom is the tail.
HEBREW: dict[str, str] = {
    "853": "[marks the direct object]",
    "5921": "on; over; against; concerning",
    "413": "to; toward; into",
    "834": "which; that; who",
    "3808": "not; no",
    "3588": "for; because; that; when",
    "1931": "he; it; that",
    "5704": "until; as far as; while",
    "4480": "from; out of; than",
    "2088": "this",
    "859": "you",
    "518": "if; whether; when",
    "5973": "with; beside",
    "854": "with; near",
    "589": "I",
    "2009": "behold; here is",
    "369": "there is not; nothing",
    "370": "where?; from where?",
    "4100": "what?; how?; why?",
    "428": "these",
    "408": "do not; let there not be",
    "1571": "also; even; moreover",
    "310": "after; behind; afterwards",
    "2063": "this [f.]",
    "1992": "they",
    "8478": "under; beneath; instead of",
    "3651": "so; thus; therefore",
    "4310": "who?",
    "996": "between; among",
    "4994": "please; now [softens a request]",
    "595": "I",
    "176": "or",
    "2005": "behold; if",
    "4616": "so that; for the sake of",
    "5048": "before; opposite; in front of",
    "3644": "like; as",
    "3426": "there is; there are",
    "6435": "lest; so that not",
    "587": "we",
    "7535": "only; except",
    "1115": "not; without; except",
    "1157": "behind; through; on behalf of",
    "3282": "because; on account of",
    "349": "how?; how!",
    "5542": "selah [a musical or liturgical mark]",
    "1077": "not",
    "4069": "why?",
    "681": "beside; near",
    "1945": "woe!; ah!",
    "346": "where?",
    "2007": "they [f.]",
    "5978": "with; beside",
    "4970": "when?",
    "4136": "opposite; in front of",
    "335": "where?; which?",
    "1097": "without; not",
    "188": "woe!; alas!",
    "3863": "if only; were it that",
    "5227": "in front of; straight ahead",
    "2486": "far be it!; God forbid",
    "1107": "apart from; besides",
    "2108": "except; besides",
    "2098": "this; which",
    "162": "ah!; alas!",
    "3884": "if not; unless",
    "577": "please!; I beg you",
    "1889": "aha!",
    "994": "please; pardon me",
    "2090": "this",
    "375": "where?",
    "575": "where?; when?",
    "1119": "in; with",
    "411": "these",
    "1975": "this; that one",
    "336": "not; where?",
    "339": "woe!; alas!",
    "1976": "this one; that one",
    "5168": "we",
}

#: Aramaic, by Strong's number. A separate table because the words are separate: Hebrew
#: `לֹא` is 3808 and Aramaic `לָא` is 3809, and a reader of Daniel meeting `דִּי` is not
#: meeting a Hebrew word at all.
ARAMAIC: dict[str, str] = {
    "1768": "that; which; who; of",
    "4481": "from; out of; by",
    "5922": "on; over; concerning",
    "3809": "not; no",
    "1836": "this",
    "6925": "before; in front of",
    "5705": "until; as far as",
    "6903": "because; corresponding to; before",
    "3606": "all; every; whole",
    "5974": "with",
    "2006": "if; whether",
    "576": "I",
    "383": "there is; there are",
    "1932": "he; it",
    "479": "those",
    "607": "you",
    "1791": "this; that",
    "1994": "them",
    "4479": "who?",
    "4101": "what?; why?",
    "3860": "therefore; but; except",
    "459": "these",
    "1668": "this [f.]",
    "1297": "but; nevertheless",
    "586": "we",
    "637": "also; moreover",
    "718": "behold!",
    "8460": "under; beneath",
    "431": "behold!",
    "581": "they",
    "1797": "that; the same",
    "1887": "behold!",
    "608": "you [pl.]",
    "3487": "[marks the direct object]",
    "870": "place; after",
    "3890": "to; toward",
    "3964": "what?",
    "2370": "behold!",
    # The Aramaic twins of Hebrew words, which Strong numbered separately.
    "409": "do not",
    "311": "after; behind",
    "5049": "before; opposite",
    "997": "between",
}

#: The pieces the tagging numbers with a letter rather than a number: the pronominal
#: suffixes, which are not lexemes of their own and so have nothing to key on but their
#: spelling. Shared between the two languages, which write them nearly alike.
#:
#: These are the pieces left standing as the word where nothing else in it is numbered —
#: `בּוֹ` is a preposition and a suffix and the suffix is what it means. A gloss here is
#: the pronoun, since that is what the reader is looking at.
BY_FORM: dict[str, str] = {
    "ו": "him; his; it",
    "ך": "you; your",
    "י": "me; my",
    "הם": "them; their",
    "כם": "you; your [pl.]",
    "נו": "us; our",
    "ם": "them; their",
    "ה": "her; it",
    "מו": "them; their",
    "הן": "them; their [f.]",
    "כה": "you; your [f.]",
    "הון": "them; their",
    "כון": "you; your [pl.]",
    "נא": "us; our",
}


#: Targum Onkelos, written out by hand (targum-internal#64). See `aramaic.py` for why this
#: and the verse's names are all that answers a Targum's words.
#:
#: **Why a hand table and not a dictionary.** Onkelos has no tagging, so a dictionary could
#: only be asked by spelling, and Jastrow files a spelling under every word of three
#: registers that shares it. Asked that way, the commonest form in Onkelos, `ית`, the object
#: marker, came back "being, existence"; `יי`, the divine name, "strong cord"; `די`,
#: "which", "palm-tree"; `כל`, "all", "bride". The 300 commonest forms are 49% of the
#: running words of the Torah, so the words a reader taps most were the words most likely
#: to be wrong — the same finding the Hebrew tables above were written from.
#:
#: **Keyed by the form as written, with its suffix on**, because a suffix is where Aramaic
#: puts the pronoun and the dictionary form is the same: `עלוהי` and `עליהון` are both
#: `עַל`. A form is looked up whole first and then with ו and one of ד ב ל כ מ taken off
#: the front, so `ובארעא` finds `ארעא` here and no row has to spell the prefixes out. That
#: is also why a form that would be a different word with its first letter read as a
#: prefix is written whole: `בית` is a house before it is ב + `ית`.
#:
#: **Left out on purpose**: forms that are two common words at once and a reader could be
#: looking at either. `עמי` is "with me" in Genesis and "my people" all through Exodus;
#: `שנא` is a tooth and a year; `קימא` is a covenant and the Living One. A wrong answer on
#: a card is worse than none, so those go to the dictionary and are left without a meaning
#: where it is not sure.
#:
#: The headwords are pointed the way Onkelos is, and a verb is filed under its perfect,
#: third person masculine singular, which is how Jastrow files it.
TARGUM: dict[str, str] = {
    # The object marker, with and without its pronoun.
    "ית": "יָת",
    "יתה": "יָת",
    "יתיה": "יָת",
    "יתהון": "יָת",
    "יתכון": "יָת",
    "יתך": "יָת",
    "יתי": "יָת",
    "יתנא": "יָת",
    "יתהין": "יָת",
    "יי": "יְיָ",
    "די": "דִּי",
    "על": "עַל",
    "עלוהי": "עַל",
    "עליהון": "עַל",
    "עלך": "עַל",
    "עלי": "עַל",
    "עלה": "עַל",
    "עלנא": "עַל",
    "עלהון": "עַל",
    "עליכון": "עַל",
    "עלוי": "עַל",
    "לא": "לָא",
    "ארי": "אֲרֵי",
    "כל": "כָּל",
    "כולא": "כָּל",
    "קדם": "קֳדָם",
    "קדמוהי": "קֳדָם",
    "קדמך": "קֳדָם",
    "קדמי": "קֳדָם",
    "קדמנא": "קֳדָם",
    "קדמיהון": "קֳדָם",
    "קדמכון": "קֳדָם",
    "אמר": "אֲמַר",
    "אמרו": "אֲמַר",
    "אמרת": "אֲמַר",
    "אמרין": "אֲמַר",
    "אמרית": "אֲמַר",
    "מימר": "אֲמַר",
    "תימר": "אֲמַר",
    "יימר": "אֲמַר",
    "נימר": "אֲמַר",
    "תימרון": "אֲמַר",
    "בר": "בַּר",
    "בני": "בַּר",
    "בנין": "בַּר",
    "בנוהי": "בַּר",
    "בנך": "בַּר",
    "ברה": "בַּר",
    "ברי": "בַּר",
    "בנהון": "בַּר",
    "בניכון": "בַּר",
    "בנא": "בַּר",
    "בנת": "בַּת",
    "בת": "בַּת",
    "בנתא": "בַּת",
    "ברתי": "בַּת",
    "ברתיה": "בַּת",
    "מן": "מִן",
    "מנה": "מִן",
    "מנהון": "מִן",
    "מנך": "מִן",
    "מני": "מִן",
    "מננא": "מִן",
    "מניה": "מִן",
    "מנכון": "מִן",
    "לה": "לְ",
    "ליה": "לְ",
    "להון": "לְ",
    "לך": "לְ",
    "לכון": "לְ",
    "לי": "לְ",
    "לנא": "לְ",
    "להין": "לְ",
    "בה": "בְּ",
    "ביה": "בְּ",
    "בהון": "בְּ",
    "בך": "בְּ",
    "בכון": "בְּ",
    "ארעא": "אַרְעָא",
    "ארע": "אַרְעָא",
    "עם": "עִם",
    "עמה": "עִם",
    "עמיה": "עִם",
    "עמך": "עִם",
    "עמהון": "עִם",
    "עמכון": "עִם",
    "עמנא": "עִם",
    "עמא": "עַמָּא",
    "עממיא": "עַמָּא",
    "הוא": "הוּא",
    "היא": "הִיא",
    "ההוא": "הַהוּא",
    "ההיא": "הַהִיא",
    "אנא": "אֲנָא",
    "אנחנא": "אֲנַחְנָא",
    "אנון": "אִנּוּן",
    "את": "אַתְּ",
    "אתון": "אַתּוּן",
    "עד": "עַד",
    "חד": "חַד",
    "חדא": "חַד",
    "לחדא": "לַחֲדָא",
    "או": "אוֹ",
    "אלהך": "אֱלָהּ",
    "אלהכון": "אֱלָהּ",
    "אלהא": "אֱלָהּ",
    "אלהנא": "אֱלָהּ",
    "אלהן": "אֱלָהּ",
    "אלהים": "אֱלָהּ",
    "אלהי": "אֱלָהּ",
    "אלההון": "אֱלָהּ",
    "אלהיה": "אֱלָהּ",
    "כהנא": "כַּהֲנָא",
    "כהניא": "כַּהֲנָא",
    "כהנין": "כַּהֲנָא",
    "יהי": "הֲוָה",
    "יהון": "הֲוָה",
    "תהי": "הֲוָה",
    "הוה": "הֲוָה",
    "הוו": "הֲוָה",
    "הות": "הֲוָה",
    "תהון": "הֲוָה",
    "אהי": "הֲוָה",
    "הויתי": "הֲוָה",
    "הויתון": "הֲוָה",
    "גבר": "גְּבַר",
    "גברא": "גְּבַר",
    "גבריא": "גְּבַר",
    "גברין": "גְּבַר",
    "הדין": "הָדֵין",
    "הדא": "הָדָא",
    "האלין": "הָאִלֵּין",
    "אלין": "אִלֵּין",
    "דא": "דָּא",
    "דין": "דֵּין",
    "דינא": "דִּינָא",
    "כמא": "כְּמָא",
    "כן": "כֵּן",
    "בכן": "בְּכֵן",
    "יומא": "יוֹמָא",
    "יומין": "יוֹמָא",
    "יומי": "יוֹמָא",
    "יום": "יוֹמָא",
    "שנין": "שַׁתָּא",
    "שתא": "שַׁתָּא",
    "שני": "שַׁתָּא",
    "תמן": "תַּמָּן",
    "מאה": "מְאָה",
    "מאתן": "מְאָה",
    "כען": "כְּעַן",
    "אף": "אַף",
    "אפי": "אַפֵּי",
    "אפוהי": "אַפֵּי",
    "עבד": "עֲבַד",
    "תעבד": "עֲבַד",
    "תעבדון": "עֲבַד",
    "יעבד": "עֲבַד",
    "מעבד": "עֲבַד",
    "עבדו": "עֲבַד",
    "עבדת": "עֲבַד",
    "עבדית": "עֲבַד",
    "עבדין": "עֲבַד",
    "יעבדון": "עֲבַד",
    "נעביד": "עֲבַד",
    "איעביד": "עֲבַד",
    "עבדא": "עַבְדָּא",
    "עבדך": "עַבְדָּא",
    "עבדיך": "עַבְדָּא",
    "עבדוהי": "עַבְדָּא",
    "קדמאה": "קַדְמָאָה",
    "מדבחא": "מַדְבְּחָא",
    "סחור": "סְחוֹר",
    "סחור סחור": "סְחוֹר",
    "כד": "כַּד",
    "רבא": "רַב",
    "רב": "רַב",
    "רבתא": "רַב",
    "רברבין": "רַב",
    "רברביא": "רַב",
    "בדיל": "בְּדִיל",
    "משכנא": "מַשְׁכְּנָא",
    "משכן": "מַשְׁכְּנָא",
    "זרעית": "זַרְעִית",
    "זרעיתהון": "זַרְעִית",
    "בתר": "בָּתַר",
    "לית": "לֵית",
    "אית": "אִית",
    "בית": "בֵּית",
    "ביתא": "בֵּית",
    "ביתיה": "בֵּית",
    "פקיד": "פַּקֵּיד",
    "מפקדך": "פַּקֵּיד",
    "פקדית": "פַּקֵּיד",
    "קודשא": "קֻדְשָׁא",
    "קודשיא": "קֻדְשָׁא",
    "אתתא": "אִתְּתָא",
    "אתת": "אִתְּתָא",
    "אתתה": "אִתְּתָא",
    "אתתיה": "אִתְּתָא",
    "אתתך": "אִתְּתָא",
    "נשיא": "אִתְּתָא",
    "כנשתא": "כְּנִשְׁתָּא",
    "יהב": "יְהַב",
    "יהבית": "יְהַב",
    "יהבו": "יְהַב",
    "תתן": "יְהַב",
    "יתן": "יְהַב",
    "מתן": "יְהַב",
    "אתן": "יְהַב",
    "יתנון": "יְהַב",
    "תתנון": "יְהַב",
    "מיא": "מַיָּא",
    "אלפין": "אֲלַף",
    "אלף": "אֲלַף",
    "קרא": "קְרָא",
    "מסאב": "מְסָאַב",
    "מסאבא": "מְסָאַב",
    "אחוהי": "אֲחָא",
    "אחוך": "אֲחָא",
    "אחוהא": "אֲחָא",
    "אחי": "אֲחָא",
    "אחוי": "אֲחָא",
    "אחיהון": "אֲחָא",
    "אחוכון": "אֲחָא",
    "אחנא": "אֲחָא",
    "אבוהי": "אַבָּא",
    "אבא": "אַבָּא",
    "אבוך": "אַבָּא",
    "אבהתהון": "אַבָּא",
    "אבי": "אַבָּא",
    "אבהתך": "אַבָּא",
    "אבוהון": "אַבָּא",
    "אבונא": "אַבָּא",
    "מליל": "מַלֵּיל",
    "מלל": "מַלֵּיל",
    "מללא": "מַלֵּיל",
    "מלילית": "מַלֵּיל",
    "בין": "בֵּין",
    "פתגמא": "פִּתְגָּמָא",
    "פתגמיא": "פִּתְגָּמָא",
    "פתגמי": "פִּתְגָּמָא",
    "תרין": "תְּרֵין",
    "תרתין": "תְּרֵין",
    "תרויהון": "תְּרֵין",
    "דמא": "דְּמָא",
    "מלכא": "מַלְכָּא",
    "מלך": "מַלְכָּא",
    "מלכי": "מַלְכָּא",
    "עוד": "עוֹד",
    "שמיא": "שְׁמַיָּא",
    "חזא": "חֲזָא",
    "חזי": "חֲזָא",
    "חזו": "חֲזָא",
    "חזית": "חֲזָא",
    "מחזי": "חֲזָא",
    "מה": "מָה",
    "ענא": "עָנָא",
    "עלתא": "עֲלָתָא",
    "עלוון": "עֲלָתָא",
    "שמה": "שְׁמָא",
    "שמא": "שְׁמָא",
    "שמיה": "שְׁמָא",
    "ידה": "יְדָא",
    "ידך": "יְדָא",
    "ידא": "יְדָא",
    "ידי": "יְדָא",
    "ידוהי": "יְדָא",
    "ידיה": "יְדָא",
    "חמשא": "חַמְשָׁא",
    "חמש": "חַמְשָׁא",
    "חמשין": "חַמְשִׁין",
    "חלף": "חֲלָף",
    "בוכרא": "בּוּכְרָא",
    "בוכריה": "בּוּכְרָא",
    "ימא": "יַמָּא",
    "שביעאה": "שְׁבִיעָאָה",
    "נסיב": "נְסֵיב",
    "יסב": "נְסֵיב",
    "תסב": "נְסֵיב",
    "נסיבו": "נְסֵיב",
    "עלם": "עָלַם",
    "עלמא": "עָלַם",
    "עלמין": "עָלַם",
    "אוריתא": "אוֹרָיְתָא",
    "שבטא": "שִׁבְטָא",
    "שבטי": "שִׁבְטָא",
    "תלתא": "תְּלָתָא",
    "תלת": "תְּלָתָא",
    "תלתין": "תְּלָתִין",
    "ברם": "בְּרַם",
    "אשתא": "אִשָּׁתָא",
    "קדיש": "קַדִּישׁ",
    "קדישין": "קַדִּישׁ",
    "דילמא": "דִּלְמָא",
    "תיכלון": "אֲכַל",
    "תיכול": "אֲכַל",
    "מיכל": "אֲכַל",
    "אכלו": "אֲכַל",
    "אכל": "אֲכַל",
    "ייכול": "אֲכַל",
    "ייכלון": "אֲכַל",
    "ארבעין": "אַרְבְּעִין",
    "ארבע": "אַרְבַּע",
    "ארבעא": "אַרְבַּע",
    "דכי": "דְּכֵי",
    "דכיא": "דְּכֵי",
    "לואי": "לֵוָאָה",
    "לואה": "לֵוָאָה",
    "סגי": "סַגִּי",
    "סגיאין": "סַגִּי",
    "תחות": "תְּחוֹת",
    "לחוד": "לְחוֹד",
    "משח": "מִשְׁחָא",
    "משחא": "מִשְׁחָא",
    "נפשא": "נַפְשָׁא",
    "נפש": "נַפְשָׁא",
    "נפשי": "נַפְשָׁא",
    "נפשך": "נַפְשָׁא",
    "מעל": "מֵעַל",
    "קרתא": "קַרְתָּא",
    "קרוי": "קַרְתָּא",
    "אמין": "אַמְּתָא",
    "אמתא": "אַמְּתָא",
    "רמשא": "רַמְשָׁא",
    "רעוא": "רַעֲוָא",
    "טורא": "טוּרָא",
    "טור": "טוּרָא",
    "משריתא": "מַשְׁרִיתָא",
    "נפק": "נְפַק",
    "נפקו": "נְפַק",
    "נפקת": "נְפַק",
    "מפק": "נְפַק",
    "יפוק": "נְפַק",
    "רבוני": "רִבּוֹן",
    "רבונך": "רִבּוֹן",
    "תורא": "תּוֹרָא",
    "תור": "תּוֹרָא",
    "תורין": "תּוֹרָא",
    "מכתשא": "מַכְתְּשָׁא",
    "חיתא": "חֵיוְתָא",
    "תקיף": "תַּקִּיף",
    "ריש": "רֵישׁ",
    "רישא": "רֵישׁ",
    "צפרא": "צַפְרָא",
    "שוי": "שַׁוִּי",
    "שויאו": "שַׁוִּי",
    "מית": "מִית",
    "מיתו": "מִית",
    "אזל": "אֲזַל",
    "אזלו": "אֲזַל",
    "איזיל": "אֲזַל",
    "איזל": "אֲזַל",
    "מצראי": "מִצְרָאָה",
    "לבושוהי": "לְבוּשָׁא",
    "לבושא": "לְבוּשָׁא",
    "לבושי": "לְבוּשָׁא",
    "דכר": "דְּכַר",
    "דכרין": "דְּכַר",
    "דכורא": "דְּכַר",
    "דהבא": "דַּהֲבָא",
    "דהב": "דַּהֲבָא",
    "בעירא": "בְּעִירָא",
    "כספא": "כַּסְפָּא",
    "כסף": "כַּסְפָּא",
    "סלעין": "סִלְעָא",
    "נטלו": "נְטַל",
    "נטל": "נְטַל",
    "גו": "גּוֹ",
    "מדברא": "מַדְבְּרָא",
    "אתו": "אֲתָא",
    "אתא": "אֲתָא",
    "אתיתי": "אֲתָא",
    "לעלא": "לְעֵילָא",
    "הלא": "הֲלָא",
    "חיא": "חֲיָא",
    "חיו": "חֲיָא",
    "ירחא": "יַרְחָא",
    "מימרא": "מֵימְרָא",
    "מימרי": "מֵימְרָא",
    "מימריה": "מֵימְרָא",
    "אתרא": "אַתְרָא",
    "אתר": "אַתְרָא",
    "יתקטל": "קְטַל",
    "אתקטלא": "קְטַל",
    "קטל": "קְטַל",
    "קטלו": "קְטַל",
    "נכסת": "נִכְסְתָא",
    "תרבא": "תַּרְבָּא",
    "חקלא": "חַקְלָא",
    "קם": "קוּם",
    "קמו": "קוּם",
    "קום": "קוּם",
    "קים": "קְיָם",
    "קימי": "קְיָם",
    "הכא": "הָכָא",
    "תרע": "תְּרַע",
    "תרעא": "תְּרַע",
    "מנחתא": "מִנְחָתָא",
    "טב": "טָב",
    "טבא": "טָב",
    "דבר": "דְּבַר",
    "דברו": "דְּבַר",
    "גלי": "גְּלֵי",
    "שלח": "שְׁלַח",
    "שלחו": "שְׁלַח",
    "ארחא": "אָרְחָא",
    "סלתא": "סֻלְתָּא",
    "ימינא": "יַמִּינָא",
    "תנינא": "תִּנְיָנָא",
    "שבעין": "שַׁבְעִין",
    "שבעא": "שַׁבְעָא",
    "שבע": "שַׁבְעָא",
    "עשרין": "עַשְׂרִין",
    "עשרא": "עַסְרָא",
    "עסרא": "עַסְרָא",
    "עסר": "עַסְרָא",
    "עובד": "עוֹבָדָא",
    "עובדא": "עוֹבָדָא",
    "עובדי": "עוֹבָדָא",
    "קרבנא": "קֻרְבָּנָא",
    "קרבנה": "קֻרְבָּנָא",
    "קרבניה": "קֻרְבָּנָא",
    "יקרב": "קְרֵיב",
    "קריב": "קְרֵיב",
    "קריבו": "קְרֵיב",
    "ארונא": "אֲרוֹנָא",
    "בסרא": "בִּסְרָא",
    "בשרא": "בִּסְרָא",
    "לות": "לְוָת",
    "לותך": "לְוָת",
    "לותי": "לְוָת",
    "לותה": "לְוָת",
    "לותיה": "לְוָת",
    "לותהון": "לְוָת",
    "עננא": "עֲנָנָא",
    "חטאתא": "חַטָּאתָא",
    "נהרא": "נַהֲרָא",
    "שטין": "שִׁטָּא",
    "רחמין": "רַחֲמִין",
    "זמנא": "זִמְנָא",
    "זמנין": "זִמְנָא",
    "קרבא": "קְרָבָא",
    "יקרא": "יְקָרָא",
    "חילא": "חֵילָא",
    "תדירא": "תְּדִירָא",
    "זהורי": "זְהוֹרִי",
    "בוסמיא": "בּוּסְמָא",
    "בעלי": "בַּעְלָא",
    "בעלה": "בַּעְלָא",
    "בעלך": "בַּעְלָא",
    "ילידת": "יְלֵיד",
    "אוליד": "יְלֵיד",
    "ילידו": "יְלֵיד",
    "כפר": "כַּפַּר",
    "יכפר": "כַּפַּר",
    "אנשא": "אֱנָשָׁא",
    "אנש": "אֱנָשָׁא",
    "חמרא": "חַמְרָא",
    "לחמא": "לַחְמָא",
    "ברכא": "בִּרְכְתָא",
    "בריך": "בְּרִיךְ",
    # Written whole because a prefix taken off them leaves another word in this table:
    # `ביתה` is his house and not ב + the object marker, `לבה` his heart and not ל + "in
    # her", `כדין` "thus" and not כ + "this". Each was found by reading every form this
    # table matched only after taking a letter off (targum-internal#64).
    "ביתה": "בֵּית",
    "ביתך": "בֵּית",
    "ביתי": "בֵּית",
    "בביתך": "בֵּית",
    "כדין": "כְּדֵין",
    "לבה": "לִבָּא",
    "לבך": "לִבָּא",
    "לבא": "לִבָּא",
    "לבי": "לִבָּא",
    "דמה": "דְּמָא",
    "כלא": "כָּל",
    "כלה": "כָּל",
    "כלנא": "כָּל",
    "בלא": "בְּלָא",
    "לעם": "עַמָּא",
    "בעם": "עַמָּא",
    "לעמה": "עַמָּא",
    "בעמה": "עַמָּא",
    "לעמך": "עַמָּא",
    "בעמך": "עַמָּא",
    "מלי": "מְלָא",
    "לאת": "אָת",
    "למה": "לְמָה",
    "כמה": "כְּמָה",
    "להלא": "לְהָלְאָה",
    "מדכר": "אַדְכַּר",
    "אדכר": "אַדְכַּר",
    "דכרני": "אַדְכַּר",
    "תדכר": "אַדְכַּר",
    "מיתי": "אַיְתִי",
    "איתי": "אַיְתִי",
    "אייתי": "אַיְתִי",
    "איתיאו": "אַיְתִי",
    "מיתך": "אֲתָא",
    "ליתך": "לֵית",
    "ליתנא": "לֵית",
    "ליתוהי": "לֵית",
    "מאית": "מִית",
    "מקים": "קוּם",
    "אקים": "קוּם",
    "במני": "מָנָא",
    "מאני": "מָנָא",
    "כמן": "כְּמַן",
    "אם": "אִם",
    "הא": "הָא",
    "קל": "קָלָא",
    "קלא": "קָלָא",
    "דר": "דָּרָא",
    "דרא": "דָּרָא",
    "עשר": "עַסְרָא",
    "שרו": "שְׁרָא",
    "שרא": "שְׁרָא",
    "לקבל": "לָקֳבֵל",
    "יתב": "יְתֵב",
    "יתבו": "יְתֵב",
    "למיתב": "יְתֵב",
    "רוח": "רוּחָא",
    "רוחא": "רוּחָא",
    "ליט": "לִיט",
    "ימות": "מִית",
    "ותב": "תָּב",
    "תב": "תָּב",
    "אזיל": "אֲזַל",
    "שמשא": "שִׁמְשָׁא",
    "נחשא": "נְחָשָׁא",
    "מלאכא": "מַלְאֲכָא",
    "מנרתא": "מְנָרְתָא",
    "רוגזא": "רוּגְזָא",
    "קטולא": "קָטוֹלָא",
    "מתקל": "מַתְקַל",
    "מתקלה": "מַתְקַל",
    "חברה": "חַבְרָא",
    "שומ": "שׁוּם",
    "ושום": "שׁוּם",
    "שום": "שׁוּם",
    "למהוי": "הֲוָה",
    "יהא": "הֲוָה",
    "רבון": "רִבּוֹן",
    "תניתא": "תִּנְיָנָא",
    "שבעת": "שַׁבְעָא",
    "רברבי": "רַב",
    "אחסנא": "אַחְסָנָא",
    "אחסנתה": "אַחְסָנָא",
    "ויחזי": "חֲזָא",
    "ואתיב": "תָּב",
    "אתיב": "תָּב",
    "שלים": "שְׁלֵים",
    "שלמא": "שְׁלָמָא",
}

#: What each headword above means, in the house style of the tables above it.
TARGUM_GLOSSES: dict[str, str] = {
    "יָת": "[marks the direct object]",
    "יְיָ": "the LORD [the divine name]",
    "דִּי": "which; that; who; of",
    "עַל": "on; over; upon; about",
    "לָא": "not; no",
    "אֲרֵי": "for; because; that; when",
    "כָּל": "all; every; any",
    "קֳדָם": "before; in front of",
    "אֲמַר": "to say; to tell",
    "בַּר": "son; child",
    "בַּת": "daughter",
    "מִן": "from; of; than",
    "לְ": "to; for",
    "בְּ": "in; with; by",
    "אַרְעָא": "land; earth; ground",
    "עִם": "with",
    "עַמָּא": "people; nation",
    "הוּא": "he; it; that",
    "הִיא": "she; it; that",
    "הַהוּא": "that",
    "הַהִיא": "that [f.]",
    "אֲנָא": "I",
    "אֲנַחְנָא": "we",
    "אִנּוּן": "they; those",
    "אַתְּ": "you",
    "אַתּוּן": "you [pl.]",
    "עַד": "until; as far as",
    "חַד": "one",
    "לַחֲדָא": "very; greatly",
    "אוֹ": "or",
    "אֱלָהּ": "God; god",
    "כַּהֲנָא": "priest",
    "הֲוָה": "to be; to become",
    "גְּבַר": "man",
    "הָדֵין": "this",
    "הָדָא": "this [f.]",
    "הָאִלֵּין": "these",
    "אִלֵּין": "these",
    "דָּא": "this [f.]",
    "דֵּין": "this",
    "דִּינָא": "judgment; law",
    "כְּמָא": "as; like; just as",
    "כֵּן": "so; thus",
    "בְּכֵן": "then; so",
    "יוֹמָא": "day",
    "שַׁתָּא": "year",
    "תַּמָּן": "there",
    "מְאָה": "hundred",
    "כְּעַן": "now",
    "אַף": "also; even",
    "אַפֵּי": "face; surface",
    "עֲבַד": "to do; to make",
    "עַבְדָּא": "servant; slave",
    "קַדְמָאָה": "first",
    "מַדְבְּחָא": "altar",
    "סְחוֹר": "around; round about",
    "כַּד": "when",
    "רַב": "great; large; chief",
    "בְּדִיל": "for the sake of; so that",
    "מַשְׁכְּנָא": "tabernacle; dwelling",
    "זַרְעִית": "family; clan",
    "בָּתַר": "after; behind",
    "לֵית": "there is not",
    "אִית": "there is",
    "בֵּית": "house",
    "פַּקֵּיד": "to command",
    "קֻדְשָׁא": "holiness; holy things",
    "אִתְּתָא": "woman; wife",
    "כְּנִשְׁתָּא": "congregation; assembly",
    "יְהַב": "to give",
    "מַיָּא": "water",
    "אֲלַף": "thousand",
    "קְרָא": "to call; to name; to read",
    "מְסָאַב": "unclean",
    "אֲחָא": "brother",
    "אַבָּא": "father",
    "מַלֵּיל": "to speak",
    "בֵּין": "between",
    "פִּתְגָּמָא": "word; matter; thing",
    "תְּרֵין": "two",
    "דְּמָא": "blood",
    "מַלְכָּא": "king",
    "עוֹד": "again; still; more",
    "שְׁמַיָּא": "heaven; sky",
    "חֲזָא": "to see",
    "מָה": "what",
    "עָנָא": "sheep; flock",
    "עֲלָתָא": "burnt offering",
    "שְׁמָא": "name",
    "יְדָא": "hand",
    "חַמְשָׁא": "five",
    "חַמְשִׁין": "fifty",
    "חֲלָף": "instead of; in place of",
    "בּוּכְרָא": "firstborn",
    "יַמָּא": "sea",
    "שְׁבִיעָאָה": "seventh",
    "נְסֵיב": "to take",
    "עָלַם": "ever; eternity",
    "אוֹרָיְתָא": "law; teaching",
    "שִׁבְטָא": "tribe",
    "תְּלָתָא": "three",
    "תְּלָתִין": "thirty",
    "בְּרַם": "but; only; however",
    "אִשָּׁתָא": "fire",
    "קַדִּישׁ": "holy",
    "דִּלְמָא": "lest; perhaps",
    "אֲכַל": "to eat",
    "אַרְבְּעִין": "forty",
    "אַרְבַּע": "four",
    "דְּכֵי": "clean; pure",
    "לֵוָאָה": "Levite",
    "סַגִּי": "much; many; great",
    "תְּחוֹת": "under; beneath",
    "לְחוֹד": "alone; only",
    "מִשְׁחָא": "oil",
    "נַפְשָׁא": "soul; life; person",
    "מֵעַל": "above; over",
    "קַרְתָּא": "city; town",
    "אַמְּתָא": "cubit",
    "רַמְשָׁא": "evening",
    "רַעֲוָא": "favour; will",
    "טוּרָא": "mountain",
    "מַשְׁרִיתָא": "camp",
    "נְפַק": "to go out",
    "רִבּוֹן": "master; lord",
    "תּוֹרָא": "ox; bull",
    "מַכְתְּשָׁא": "plague; affliction",
    "חֵיוְתָא": "animal; living creature",
    "תַּקִּיף": "strong; severe",
    "רֵישׁ": "head; beginning; chief",
    "צַפְרָא": "morning",
    "שַׁוִּי": "to put; to set; to make",
    "מִית": "to die",
    "אֲזַל": "to go",
    "מִצְרָאָה": "Egyptian",
    "לְבוּשָׁא": "garment; clothing",
    "דְּכַר": "male",
    "דַּהֲבָא": "gold",
    "בְּעִירָא": "cattle; livestock",
    "כַּסְפָּא": "silver; money",
    "סִלְעָא": "sela [a coin]",
    "נְטַל": "to set out; to lift; to carry",
    "גּוֹ": "inside; within",
    "מַדְבְּרָא": "wilderness",
    "אֲתָא": "to come",
    "לְעֵילָא": "above; upward",
    "הֲלָא": "is it not?; surely",
    "חֲיָא": "to live",
    "יַרְחָא": "month; moon",
    "מֵימְרָא": "word; the Word [of the LORD]",
    "אַתְרָא": "place",
    "קְטַל": "to kill",
    "נִכְסְתָא": "sacrifice",
    "תַּרְבָּא": "fat",
    "חַקְלָא": "field",
    "קוּם": "to rise; to stand",
    "קְיָם": "covenant",
    "הָכָא": "here",
    "תְּרַע": "gate; door",
    "מִנְחָתָא": "meal offering",
    "טָב": "good",
    "דְּבַר": "to lead; to take",
    "גְּלֵי": "revealed; to reveal",
    "שְׁלַח": "to send",
    "אָרְחָא": "way; road",
    "סֻלְתָּא": "fine flour",
    "יַמִּינָא": "right [hand or side]",
    "תִּנְיָנָא": "second",
    "שַׁבְעִין": "seventy",
    "שַׁבְעָא": "seven",
    "עַשְׂרִין": "twenty",
    "עַסְרָא": "ten",
    "עוֹבָדָא": "deed; work",
    "קֻרְבָּנָא": "offering",
    "קְרֵיב": "to come near; to offer",
    "אֲרוֹנָא": "ark; chest",
    "בִּסְרָא": "flesh; meat",
    "לְוָת": "to; toward; with",
    "עֲנָנָא": "cloud",
    "חַטָּאתָא": "sin offering; sin",
    "נַהֲרָא": "river",
    "שִׁטָּא": "acacia",
    "רַחֲמִין": "mercy; compassion",
    "זִמְנָא": "time; occasion",
    "קְרָבָא": "battle; war",
    "יְקָרָא": "glory; honour",
    "חֵילָא": "army; strength; wealth",
    "תְּדִירָא": "continually",
    "זְהוֹרִי": "scarlet",
    "בּוּסְמָא": "spice",
    "בַּעְלָא": "husband; owner",
    "יְלֵיד": "to bear; to beget",
    "כַּפַּר": "to atone",
    "אֱנָשָׁא": "man; person; mankind",
    "חַמְרָא": "wine",
    "לַחְמָא": "bread; food",
    "בִּרְכְתָא": "blessing",
    "בְּרִיךְ": "blessed",
    "כְּדֵין": "thus; so",
    "לִבָּא": "heart",
    "בְּלָא": "without",
    "מְלָא": "to fill; full",
    "אָת": "sign",
    "לְמָה": "why",
    "כְּמָה": "how many; how much",
    "לְהָלְאָה": "onward; further",
    "אַדְכַּר": "to remember; to mention",
    "אַיְתִי": "to bring",
    "מָנָא": "vessel",
    "כְּמַן": "lying in wait",
    "אִם": "if",
    "הָא": "behold; here is",
    "קָלָא": "voice; sound",
    "דָּרָא": "generation",
    "שְׁרָא": "to dwell; to camp; to begin",
    "לָקֳבֵל": "opposite; facing; in front of",
    "יְתֵב": "to sit; to dwell",
    "רוּחָא": "wind; spirit",
    "לִיט": "cursed",
    "תָּב": "to return",
    "שִׁמְשָׁא": "sun",
    "נְחָשָׁא": "copper; bronze",
    "מַלְאֲכָא": "angel; messenger",
    "מְנָרְתָא": "lampstand",
    "רוּגְזָא": "anger",
    "קָטוֹלָא": "killer",
    "מַתְקַל": "weight",
    "חַבְרָא": "companion; neighbour",
    "שׁוּם": "name [of]",
    "אַחְסָנָא": "inheritance; possession",
    "שְׁלֵים": "complete; whole; at peace",
    "שְׁלָמָא": "peace; welfare",
}


def gloss_for(lexeme: str | None, form: str) -> str:
    """The hand-written gloss for one closed-class word, or "" where there is none.

    By number where the tagging gave one, by spelling where it gave a letter. The two
    language tables are asked together and need no flag between them: Strong numbered
    the whole lexicon once, so `3808` is the Hebrew `לֹא` and `3809` the Aramaic `לָא`
    and no number means two things.
    """
    number = (lexeme or "").strip().split(" ")[0].lstrip("H")
    if number:
        for table in (HEBREW, ARAMAIC):
            if number in table:
                return table[number]
    return BY_FORM.get(form, "")
